## Numpy intro

In [3]:
# Двуизмерни списъци, функции върху матрици
# requirements.txt pandas, matplotlib, seaborn, jupyterlab
import numpy as np

# np.array()

In [4]:
SIZE = 2000000
l1 = list(range(SIZE))
l2 = list(range(SIZE))

def python_list():
    result = []

In [17]:
l = range(10)
a1 = np.array(l)
a1.shape


[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


25

In [33]:
# numpy.full(shape, full_value, dtype) 
a2 = np.full((5,5), 3)
print(a2)
a2.size

a3 = a1.reshape((5,2))
print(a3)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [37]:
# All arithmetical operations are done 1 to 1 between two massives
a3[2][1] # Not good
print(a3[2,1]) # The way to go

5


In [64]:
# matrix with 1 values in elements above main diagonal

m1 = np.flip(np.tri(10, 10, 0))
print(m1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
